### ISSUE TITLE
imports incompatible with python3

### ISSUE THREAD

**Issue by wasaga** [pomerium/enterprise-client-python#10]
https://github.com/pomerium/enterprise-client-python/commit/abad4c02fdffed4c3d3e0eb694e5c6a5720e3a54#r86119074

(same issue across other files)

causes

```
>>> import pomerium.client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/denis/pomerium/enterprise-client-python/src/pomerium/client.py", line 8, in <module>
    from pomerium.pb.routes_pb2_grpc import RouteServiceStub
  File "/Users/denis/pomerium/enterprise-client-python/src/pomerium/pb/routes_pb2_grpc.py", line 5, in <module>
    from . import routes_pb2 as routes__pb2
  File "/Users/denis/pomerium/enterprise-client-python/src/pomerium/pb/routes_pb2.py", line 19, in <module>
    import policy_pb2 as policy__pb2
ModuleNotFoundError: No module named 'policy_pb2'
>>> from pomerium.pb.routes_pb2 import SetRouteRequest, Route
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/denis/pomerium/enterprise-client-python/src/pomerium/pb/routes_pb2.py", line 19, in <module>
    import policy_pb2 as policy__pb2
ModuleNotFoundError: No module named 'policy_pb2'
```

**Comment by desimone** [comment]
putting back in ready queue

**Comment by calebdoxsey** [comment]
I had to write a bash script to fix the imports.
