### ISSUE TITLE
SDK cannot load

### ISSUE THREAD

**Issue by wasaga** [pomerium/enterprise-client-python#11]
https://github.com/pomerium/enterprise-client-python/actions/runs/3019748836/jobs/4855978582

```
>>> from pomerium.pb.routes_pb2 import SetRouteRequest, Route
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/pomerium/pb/routes_pb2.py", line 17, in <module>
    from envoy.config.cluster.v3 import cluster_pb2 as envoy_dot_config_dot_cluster_dot_v3_dot_cluster__pb2
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/envoy/config/cluster/v3/cluster_pb2.py", line 14, in <module>
    from envoy.config.cluster.v3 import circuit_breaker_pb2 as envoy_dot_config_dot_cluster_dot_v3_dot_circuit__breaker__pb2
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/envoy/config/cluster/v3/circuit_breaker_pb2.py", line 14, in <module>
    from envoy.config.core.v3 import base_pb2 as envoy_dot_config_dot_core_dot_v3_dot_base__pb2
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/envoy/config/core/v3/base_pb2.py", line 15, in <module>
    from envoy.config.core.v3 import address_pb2 as envoy_dot_config_dot_core_dot_v3_dot_address__pb2
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/envoy/config/core/v3/address_pb2.py", line 14, in <module>
    from envoy.config.core.v3 import socket_option_pb2 as envoy_dot_config_dot_core_dot_v3_dot_socket__option__pb2
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/envoy/config/core/v3/socket_option_pb2.py", line 14, in <module>
    from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/udpa/annotations/status_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Users/denis/pomerium/snippets/2022/10/6/psdk/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

the fix is to set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`

**Comment by calebdoxsey** [comment]
The recommended fix does not work. Downgrading protobuf sort of works.

**Comment by wasaga** [comment]
> The recommended fix does not work

did you try on Mac or on Linux?
